name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up QEMU (for multi-platform builds)
      uses: docker/setup-qemu-action@v1

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: aqibjavaid817/sadat-app
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        docker-compose build
        docker-compose push

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Establish SSH Connection
      env:
        SSHPASS: ${{ secrets.SERVER_PASSWORD }}
      run: |
        sshpass -e ssh -o StrictHostKeyChecking=no -p 22 sadat@54.211.80.32 "cd /var/php-app/sadat-test && ./deploy.sh"
