name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up QEMU (for multi-platform builds)
      uses: docker/setup-qemu-action@v1

    - name: Build and push Docker image
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        IMAGE_NAME: aqibjavaid817/sadat-app
      run: |
        docker build -t $IMAGE_NAME .
        echo $DOCKER_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push $IMAGE_NAME
